version: 2
updates:
  # .NET
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  # JavaScript
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # GoLang
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # Bash (using GitHub Actions for bash scripts)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
